package com.example.Clinica;

import com.example.Clinica.security.user.*;
import com.example.Clinica.security.user.repository.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.Set;


@SpringBootApplication
public class ClinicaApplication {


	public static void main(String[] args) {
		SpringApplication.run(ClinicaApplication.class, args);
	}

	@Bean
	CommandLineRunner init(UserRepository userRepository) {
		return  args -> {

			PermissionEntity patientRead = PermissionEntity.builder()
					.name(PermissionName.PATIENT_READ)
					.build();

			PermissionEntity patientCreate = PermissionEntity.builder()
					.name(PermissionName.PATIENT_CREATE)
					.build();

			PermissionEntity patientUpdate = PermissionEntity.builder()
					.name(PermissionName.PATIENT_UPDATE)
					.build();

			PermissionEntity userRead = PermissionEntity.builder()
					.name(PermissionName.USER_READ)
					.build();

			PermissionEntity userCreate = PermissionEntity.builder()
					.name(PermissionName.USER_CREATE)
					.build();

			PermissionEntity userUpdate = PermissionEntity.builder()
					.name(PermissionName.USER_UPDATE)
					.build();

			PermissionEntity userDelete = PermissionEntity.builder()
					.name(PermissionName.USER_DELETE)
					.build();

			PermissionEntity roleAssign = PermissionEntity.builder()
					.name(PermissionName.ROLE_ASSIGN)
					.build();

			PermissionEntity exportData = PermissionEntity.builder()
					.name(PermissionName.EXPORT_DATA)
					.build();

			PermissionEntity admissionCreate = PermissionEntity.builder()
					.name(PermissionName.ADMISSION_CREATE)
					.build();

			PermissionEntity admissionUpdate = PermissionEntity.builder()
					.name(PermissionName.ADMISSION_UPDATE)
					.build();

			PermissionEntity admissionClose = PermissionEntity.builder()
					.name(PermissionName.ADMISSION_CLOSE)
					.build();

			PermissionEntity admissionReadAll = PermissionEntity.builder()
					.name(PermissionName.ADMISSION_READ_ALL)
					.build();

			PermissionEntity reportPatients = PermissionEntity.builder()
					.name(PermissionName.REPORT_PATIENTS)
					.build();

			PermissionEntity reportFinancial = PermissionEntity.builder()
					.name(PermissionName.REPORT_FINANCIAL)
					.build();

			PermissionEntity auditLogs = PermissionEntity.builder()
					.name(PermissionName.AUDIT_LOGS)
					.build();


			Role rolAdmin = Role.builder()
							.name(RoleName.ROLE_ADMIN)
							.permissions(Set.of(
									patientRead, patientCreate, patientUpdate,
									userRead, userCreate, userUpdate, userDelete,
									roleAssign, exportData, admissionCreate,
									admissionUpdate, admissionClose, admissionReadAll,
									reportPatients, reportFinancial, auditLogs
							))
							.build();
			Role rolDoctor = Role.builder()
							.name(RoleName.ROLE_DOCTOR)
							.permissions(Set.of(
									patientRead, patientUpdate, admissionCreate,
									admissionUpdate, admissionClose, admissionReadAll,
									reportPatients
							))
							.build();
			Role rolNurse = Role.builder()
							.name(RoleName.ROLE_NURSE)
							.permissions(Set.of(
									patientRead, admissionCreate,
									admissionUpdate, admissionReadAll
							))
							.build();
		};
	};

}




/* HISTORIAL DEL PACIENTE

CREATE TABLE clinical_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    admission_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL, -- El User (Nurse/Doctor)
    note_type VARCHAR(50), -- 'EVOLUTION', 'INITIAL_ASSESSMENT', 'DISCHARGE_SUMMARY'
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notes_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_notes_admission FOREIGN KEY (admission_id) REFERENCES admissions(id),
    CONSTRAINT fk_notes_user FOREIGN KEY (professional_id) REFERENCES users(id)
);


 */