ALTER TABLE users
    ADD COLUMN email VARCHAR(255) UNIQUE NOT NULL,
    ADD COLUMN account_no_expired BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN account_no_locked BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN credentials_no_expired BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN is_enabled BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permissions_roles
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permissions
        FOREIGN KEY (permission_id)
        REFERENCES permissions(id)
        ON DELETE CASCADE
);

CREATE TABLE user_permissions (
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, permission_id),

    CONSTRAINT fK_user_permissions_users
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_permissions_permissions
        FOREIGN KEY (permission_id)
        REFERENCES permissions(id)
        ON DELETE CASCADE
);