CREATE TYPE clinical_note_type AS ENUM ('EVOLUTION', 'INITIAL_ASSESSMENT', 'DISCHARGE_SUMMARY');

CREATE TABLE IF NOT EXISTS clinical_notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        patient_id BIGINT NOT NULL,
        admission_id BIGINT NOT NULL,
        professional_id BIGINT NOT NULL,
        note_type clinical_note_type NOT NULL,
        content TEXT NOT NULL,

        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        created_by BIGINT,
        updated_by BIGINT,
        deleted_at TIMESTAMP,

        CONSTRAINT fk_notes_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
        CONSTRAINT fk_notes_admission FOREIGN KEY (admission_id) REFERENCES admissions(id),
        CONSTRAINT fk_notes_user FOREIGN KEY (professional_id) REFERENCES users(id)
);

CREATE INDEX idx_clinical_notes_patient_id
    ON clinical_notes(patient_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_clinical_notes_admission_id
    ON clinical_notes(admission_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_clinical_notes_patient_created
    ON clinical_notes (patient_id, created_at DESC)
    WHERE deleted_at IS NULL;