CREATE TABLE IF NOT EXISTS doctor_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    years_of_experience INTEGER,
    work_start_time TIME,
    work_end_time TIME,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_doctor_profiles_users
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_doctor_profiles_user_id ON doctor_profiles(user_id);

CREATE TABLE IF NOT EXISTS doctor_specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS doctor_specialty_map (
    doctor_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    PRIMARY KEY (doctor_id, specialty_id),

    CONSTRAINT fk_doctor_specialty_map_doctor_profiles
        FOREIGN KEY (doctor_id)
        REFERENCES doctor_profiles(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_doctor_specialty_map_doctor_specialties
        FOREIGN KEY (specialty_id)
        REFERENCES doctor_specialties(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS doctor_working_days (
    doctor_id BIGINT NOT NULL,
    day VARCHAR(50),
    PRIMARY KEY (doctor_id, day),

    CONSTRAINT fk_doctor_working_days_doctor_profiles
        FOREIGN KEY (doctor_id)
        REFERENCES doctor_profiles(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_doctor_working_days_doctor_id ON doctor_working_days(doctor_id);

CREATE TABLE IF NOT EXISTS nurse_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_start_time TIME,
    work_end_time TIME,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_nurse_profile_users
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS nurse_working_days (
    nurse_id BIGINT NOT NULL,
    day VARCHAR(50),
    PRIMARY KEY (nurse_id, day),

    CONSTRAINT fk_nurse_working_days_nurse_profiles
        FOREIGN KEY (nurse_id)
        REFERENCES nurse_profiles(id)
        ON DELETE CASCADE
);